Musey/urls.py
from django.conf.urls import patterns, include, url
from museyapp import views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Musey.views.home', name='home'),
    # url(r'^Musey/', include('Musey.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^$', views.index, name='index'),
     url(r'^musey/', include('museyapp.urls')),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^signup', views.signup, name='signup'),
     url(r'^login', views.login, name='login'),
     url(r'^something/hard/to/guess/', include('paypal.standard.ipn.urls')),
) 
)

museyapp/urls.py
from django.conf.urls import patterns, url
from museyapp import views
from django.conf import settings
urlpatterns = patterns('',
url(r'^events/(?P<event_id>\d+)|/$', views.events, name='events'),
url(r'^projects/(?P<prjct_id>\d+)|/$', views.projects, name='projects'),
url(r'^artists/(?P<artist_id>\d+)|/$', views.artist, name='artist'),
url(r'^events/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
url(r'^charge/$', views.charge, name="charge"),
url(r'projects/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),

url(r'^paypal/$', views.paypal, name='paypal'), 

)

museyapp/models.py
from django.db import models
from django.contrib import admin
# Create your models here.

#General User Table
class User(models.Model):
    #fields
    email_address=models.EmailField(primary_key=True)
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    password=models.CharField(('password'),max_length=50)
    
    #what to return when object is get
    def __unicode__(self):
        return self.email_address #returning primary key to identify user
   

class Artist(models.Model):
    #fields
    
    #Basics
    profile_pic=models.ImageField(upload_to='images/artist/pics')
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    nick_name=models.CharField(max_length=20,blank=True)
    MALE='M'
    FEMALE='F'
    GENDER=((MALE, 'Male'),(FEMALE,'Female'))
    gender = models.CharField(max_length=1,choices=GENDER,default=MALE)
    location=models.CharField(max_length=100)
    bank_acct=models.CharField(max_length=20)
    
    #Work
    statement=models.CharField(max_length=100)
    self_desc=models.TextField(max_length=500)
    recvd_donation=models.PositiveIntegerField(default=0)
    
    #Contact
    email_id=models.EmailField()
    phone=models.CharField(max_length=50,blank=True)
    
    #Artist_Media Links
    Facebook=models.URLField(blank=True)
    twitter=models.URLField(blank=True)
    myspace=models.URLField(blank=True)
    youtube=models.URLField(blank=True)
    tumblr=models.URLField(blank=True)
    soundcloud=models.URLField(blank=True)
    personal_link=models.URLField(blank=True)
    
    def __unicode__(self):
        return self.first_name +" "+self.last_name



    
    
class Event(models.Model):
    #fields
    main_title=models.CharField(max_length=50)
    Subtitle=models.CharField(max_length=50)
    datefrom=models.DateField()
    dateto=models.DateField()
    timefrom=models.TimeField()
    timeto=models.TimeField()
    Location=models.CharField(max_length=100)
    Remarks=models.TextField(max_length=500)
    Description=models.TextField(max_length=500)
    external_link=models.URLField()
    
    #what to return when object is get
    def __unicode__(self):
        return self.main_title
    
    def getnext(self):
        events=Event.objects.all()
        size=len(events)
        for x in xrange(size):
            if self.id==events[x].id:
                if x+1 != size:
                    return events[x+1]
                else:
                    return events[0]
    
    def getprv(self):
        events=Event.objects.all()
        size=len(events)
        for x in xrange(size):
            if self.id==events[x].id:
                if x-1 >-1:
                    return events[x-1]
                else:
                    return events[size-1]    
    #Advocates (keep void)
  


class Event_Images(models.Model):
    #code
    def upload_to(instance, filename):
        return 'images/events/'+instance.event.main_title+'/'+filename
    event=models.ForeignKey(Event)
    image=models.ImageField(upload_to=upload_to)
    default=models.BooleanField()
    class Meta:
        unique_together = ('image', 'event',)
   
class Event_Artist(models.Model):
    artist=models.ForeignKey(Artist)
    role=models.CharField(max_length=20)
    event=models.ForeignKey(Event)
    class Meta:
        unique_together = ('artist', 'event',)
    def __unicode__(self):
        artist=self.artist
        return artist.first_name+" "+artist.last_name + '('+ self.role + ')'    

class Event_Donations(models.Model):
    #code
    event=models.ForeignKey(Event)
    doner_account=models.ForeignKey(User)
    donation_amount=models.PositiveIntegerField(default=0)
    donation_location=models.CharField(max_length=100)
    donation_time=models.DateTimeField()
    payment_method=models.CharField(max_length=10,choices=(('p','PayPal'),('c','CreditCard')))

class Event_Sharing(models.Model):
    #code
    user_acct=models.ForeignKey(User)
    event=models.ForeignKey(Event)
    time=models.DateTimeField()
    media=models.CharField(max_length=20)

#--------------------models for stripe-------------------------------#
#--------------------------------------------------------------------#


from django.conf import settings
 
class Sale(models.Model):
    def __init__(self, *args, **kwargs):
        super(Sale, self).__init__(*args, **kwargs)
 
        # bring in stripe, and get the api key from settings.py
        import stripe
        stripe.api_key = settings.STRIPE_API_KEY
 
        self.stripe = stripe
 
    # store the stripe charge id for this sale
    charge_id = models.CharField(max_length=32)
 
    # you could also store other information about the sale
    # but I'll leave that to you!
 
    def charge(self, price_in_cents, number, exp_month, exp_year, cvc):
        """
        Takes a the price and credit card details: number, exp_month,
        exp_year, cvc.
 
        Returns a tuple: (Boolean, Class) where the boolean is if
        the charge was successful, and the class is response (or error)
        instance.
        """
 
        if self.charge_id: # don't let this be charged twice!
            return False, Exception(message="Already charged.")
 
        try:
            response = self.stripe.Charge.create(
                amount = price_in_cents,
                currency = "usd",
                card = {
                    "number" : number,
                    "exp_month" : exp_month,
                    "exp_year" : exp_year,
                    "cvc" : cvc,
 
                    #### it is recommended to include the address!
                    #"address_line1" : self.address1,
                    #"address_line2" : self.address2,
                    #"daddress_zip" : self.zip_code,
                    #"address_state" : self.state,
                },
                description='Thank you for your purchase!')
 
            self.charge_id = response.id
 
        except self.stripe.CardError, ce:
            # charge failed
            return False, ce
 
        return True, response
    
#-----------------------End models of stripe----------------------------------#
#-----------------------------------------------------------------------------#

museyapp/forms.py
from django.forms import ModelForm, Widget
from django import forms
from datetime import date
from museyapp import models
class UserForm(ModelForm):
    #code
    
    class Meta:
        model=models.User
        widgets = {'password': forms.PasswordInput(),}
    def __init__(self,*args, **kwargs):
            super(UserForm, self).__init__(*args, **kwargs)
            for fname,field in self.fields.items():
                field.widget.attrs['class'] = 'ninput'    


class LoginForm(forms.Form):
    
       email_address=forms.EmailField()
       password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'ninput'}))
       
       email_address.widget.attrs['class'] = 'ninput'
       
       
       
       
#-----------------------------stripe forms--------------------------------#
#-------------------------------------------------------------------------#

class CreditCardField(forms.IntegerField):
    def clean(self, value):
        """Check if given CC number is valid and one of the
           card types we accept"""
        if value and (len(value) < 13 or len(value) > 16):
            raise forms.ValidationError("Please enter in a valid "+\
                "credit card number.")
        return super(CreditCardField, self).clean(value)
 
class CCExpWidget(forms.MultiWidget):
    """ Widget containing two select boxes for selecting the month and year"""
    def decompress(self, value):
        return [value.month, value.year] if value else [None, None]
 
    def format_output(self, rendered_widgets):
        html = u' / '.join(rendered_widgets)
        return u'<span style="white-space: nowrap;">%s</span>' % html
 
class CCExpField(forms.MultiValueField):
    EXP_MONTH = [(x, x) for x in xrange(1, 13)]
    EXP_YEAR = [(x, x) for x in xrange(date.today().year,
                                       date.today().year + 15)]
    default_error_messages = {
        'invalid_month': u'Enter a valid month.',
        'invalid_year': u'Enter a valid year.',
    }
 
    def __init__(self, *args, **kwargs):
        errors = self.default_error_messages.copy()
        if 'error_messages' in kwargs:
            errors.update(kwargs['error_messages'])
        fields = (
            forms.ChoiceField(choices=self.EXP_MONTH,
                error_messages={'invalid': errors['invalid_month']}),
            forms.ChoiceField(choices=self.EXP_YEAR,
                error_messages={'invalid': errors['invalid_year']}),
        )
        super(CCExpField, self).__init__(fields, *args, **kwargs)
        self.widget = CCExpWidget(widgets =
            [fields[0].widget, fields[1].widget])
 
    def clean(self, value):
        exp = super(CCExpField, self).clean(value)
        if date.today() > exp:
            raise forms.ValidationError(
            "The expiration date you entered is in the past.")
        return exp
 
    def compress(self, data_list):
        if data_list:
            if data_list[1] in forms.fields.EMPTY_VALUES:
                error = self.error_messages['invalid_year']
                raise forms.ValidationError(error)
            if data_list[0] in forms.fields.EMPTY_VALUES:
                error = self.error_messages['invalid_month']
                raise forms.ValidationError(error)
            year = int(data_list[1])
            month = int(data_list[0])
            # find last day of the month
            day = monthrange(year, month)[1]
            return date(year, month, day)
        return None
 
class SalePaymentForm(forms.Form):
    number = CreditCardField(required=True, label="Card Number")
    expiration = CCExpField(required=True, label="Expiration")
    cvc = forms.IntegerField(required=True, label="CCV Number",
        max_value=9999, widget=forms.TextInput(attrs={'size': '4'}))
 
    def clean(self):
        """
        The clean method will effectively charge the card and create a new
        Sale instance. If it fails, it simply raises the error given from
        Stripe's library as a standard ValidationError for proper feedback.
        """
        cleaned = super(SalePaymentForm, self).clean()
 
        if not self.errors:
            number = self.cleaned_data["number"]
            exp_month = self.cleaned_data["expiration"].month
            exp_year = self.cleaned_data["expiration"].year
            cvc = self.cleaned_data["cvc"]
 
            sale = Sale()
 
            # let's charge $10.00 for this particular item
            success, instance = sale.charge(1000, number, exp_month,
                                                exp_year, cvc)
 
            if not success:
                raise forms.ValidationError("Error: %s" % instance.message)
            else:
                instance.save()
                # we were successful! do whatever you will here...
                # perhaps you'd like to send an email...
                pass
 
        return cleaned
#    
##--------------------------------End Stripe Forms--------------------------------#
##--------------------------------------------------------------------------------#

museyapp/views.py
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render
from museyapp import forms
from museyapp.models import Event,User,Artist, Sale
from django.forms.util import ErrorList

def index(request):
    
    #login=req.session['login']='Log In'
    
    #login=request.session['login']
    return render(request, 'museyapp/index.html',{'login':login,} )

def signup(request):
   
    if request.method =='POST':
        user_form=forms.UserForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            return HttpResponse('form saved')
    else:
        user_form=forms.UserForm()
    return render(request, 'museyapp/signup.html', {'form': user_form,})
    
def login(request):
    
    
    if request.method =='POST':
        
        login_form=forms.LoginForm(request.POST)
        
        if login_form.is_valid():
            print login_form.cleaned_data['password']
            if not User.objects.filter(email_address=login_form.cleaned_data['email_address'],password=login_form.cleaned_data['password']):
                errors = login_form._errors.setdefault("email_address", ErrorList())
                errors.append(u"Invalid Email Id or Password")
            else:
                 request.session['login']='Logoff'
                 return HttpResponseRedirect('/')
            
    else:
        login_form=forms.LoginForm()
    return render(request,'museyapp/login.html',{'form':login_form,})    
    
def events(request, event_id=None):
    events=Event.objects.all()
    if len(events)>0:
        if not event_id:
            event=events[0]
            
        else:
            event=Event.objects.get(id=event_id)
            
        prv_event=event.getprv()
        nxt_event=event.getnext()
        event_img=event.event_images_set.get(default=True)
    else:
        event=None
    return render(request, 'museyapp/events.html', {'event': event,'prv_event':prv_event,'nxt_event':nxt_event,'event_img':event_img})

def projects(request, prjct_id):
    event=Event.objects.get(id=prjct_id)
    event_img=event.event_images_set.get(default=True)
    return render(request, 'museyapp/projects.html', {'event': event,'event_img':event_img})


def artist(request, artist_id):
    artist=Artist.objects.get(id=artist_id)
    return render(request,'museyapp/artists.html',{'artist':artist})

def charge(request):
    if request.method == "POST":
        form = forms.SalePaymentForm(request.POST)
 
        if form.is_valid(): # charges the card
            return HttpResponse("Success! We've charged your card!")
    else:
        form = forms.SalePaymentForm()
 
    return render_to_response("museyapp/charge.html",
                        RequestContext( request, {'form': form} ) )



#------------------------------PayPal-------------------------------#
#-------------------------------------------------------------------#

from paypal.standard.forms import PayPalPaymentsForm
from django.conf import settings
from django.core.urlresolvers import reverse
def paypal(request):
# What you want the button to do.
    paypal_dict = {
    "business": settings.PAYPAL_RECEIVER_EMAIL,
    "amount": "1.00",
    "item_name": "name of the item",
    "invoice": "unique-invoice-id",
    "notify_url": "%s%s" % (settings.SITE_NAME, reverse('paypal-ipn')),
    "return_url": "http://www.example.com/your-return-location/",
    "cancel_return": "http://www.example.com/your-cancel-location/",}
# Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form.sandbox()}
    return render_to_response("paypal.html", context)

museyapp/templates/museyapp/artists.html
{% extends "museyapp/base.html" %}
{% load static %}
{% block content %}
    <div id="page">
      <div id="content">
        <section id="top">
          <div class="row-fluid black-box">
            <div class="container">
              <div class="pull-center">
                <a href="../index.html"><img src="../img/musey-logo.png" ></a>
                <a href="project-onafence.html" class="menu-btn m-arrow"><img src="../img/menu-left-arrow.png"></a>
                <!--
                <a href="#menu" class="menu-btn"><img src="../img/menu-btn.png"></a>-->
              </div>
                
              </div>
              
            </div>
          </div>
        </section>
      </div>
      
    </div>  
    
    <div class="container home-bottom">
      <div class="ap">
        <h1>{{artist.first_name}} {{artist.last_name}}</h1>
        <div class="bottom-divider"></div>
        
        <div class="apic">
          <img src={{artist.profile_pic.url}} class="artist-pic">
        </div>

        <div class="bottom-divider"></div>
        <div>
          <h4 class="a-loc">{{artist.location}}</h4>
          <h2>NY</h2>
        </div>
        <div class="bottom-divider"></div>
        <p class="ap-text"><span class="bold-text1">
{{artist.first_name}} {{artist.last_name}}</span>
          {{artist.self_desc}}
        </p>
        <!--
        <div class="bold-divider"></div>
        <a class="ap-btext">On a Fence</a>
        -->
        <div class="bold-divider"></div>
        {% for e in artist.event_artist_set.all%}
        <a class="ap-btext2" href="/musey/events/{{e.event.id}}">{{e.event.main_title}}</a>
        <div class="bold-divider"></div>
        {% endfor %}
  
    </div>
    <footer class="container-fluid fotternav">
      <div class="container">
        <div class="f-nav">
          <a href="about.html" class="f-text002">About us</a>
          <a href="mailto:someone@example.com?Subject=Hello%20again" target="_top" class="f-text002">Contact</a>
          <a href="event-kingkong.html" ><img src="../img/footer-logo.png"></a>
        </div>
      </div>
    </footer> 
   
{% endblock %}  

museyapp/templates/museyapp/charge.html
<html>
<head>
  <title>Stripe Example</title>
</head>
<body>
 
<div class="wrapper">
 
  {% for key, value in form.errors.items %}
      <p>{{ value }}</p>
  {% endfor %}
 
  <form action="" method="post">{% csrf_token %}
 
    {% for field in form %}
      <div class="field-wrapper">
 
        <div class="field-label">
          {{ field.label_tag }}:
        </div>
 
        <div class="field-field">
          {{ field }}
          {{ field.errors }}
        </div>
 
      </div>
    {% endfor %}
 
    <br>
    <input type="submit" value="Charge Me!" />
  </form>
 
</div>
 
</body>
</html>

museyapp/templates/museyapp/events.html
{% extends "museyapp/base.html" %}
{% load static %}
{% block content %}
    <div id="page">
      <div id="content">
        <section id="top">
          <div class="row-fluid black-box">
            <div class="container">
              <div class="pull-center">
                <a href="index.html"><img src=" {% static 'museyapp/img/musey-logo.png' %}" ></a>
                <div class="menu-btn">
                <a href="#menu" class="menu-btn"><img src=" {% static 'museyapp/img/menu-btn.png' %}"></a></p>
              </div>
                
              </div>
              
            </div>
          </div>
        </section>
      </div>
      <nav id="menu">
        <ul>
          <li class="Selected"><a href="index.html"><span class="home-icon"></span>Home</a></li>
          <li><a href="signup.html"><span class="singup-icon"></span>Sign up | Log in</a></li>
          <li><a href="account-setting.html"><span class="accounts-icon"></span>Account settings</a></li>
        </ul>
        <div class="nav-musey-logo"><a href="index.html"><img src=" {% static 'museyapp/img/nav-musey-logo.png' %} "></a></div>
      </nav>
    </div>  
    <div class="container home-bottom">
      <img src={{event_img.image.url}}>
      
      <a href="/musey/events/{{prv_event.id}}" class="mleft-arr"></a>
      <a href="/musey/events/{{nxt_event.id}}" class="mright-arr"></a>

      <div class="e-detail">
        <span class="date">{{event.Time}}</span>
        <div class="event-title">
          <h3>{{event.main_title}}</h3>
          <h6>{{event.Subtitle}}</h6>
          <div class="bottom-divider"></div>
          
          {% for e_artist in event.event_artist_set.all  %}
          <h5>{{e_artist.artist.first_name}} {{e_artist.artist.last_name}}</h5>
          {% endfor %}
        </div>
        <a href="/musey/projects/{{event.id}}" class="dright-arrow"><img src="{% static 'museyapp/img/small-right-arrow.png' %}"></a>
      </div>
      <a class="gs-btn" href="project-onafence-thankyou.html">Say <strong>"Thanks"</strong> to {{event.Subtitle}}</a>
    </div>
    <footer class="container-fluid fotternav">
      <div class="container">
        <div class="f-nav">
          <a href="about.html" class="f-text002">About us</a>
          <a href="mailto:someone@example.com?Subject=Hello%20again" target="_top" class="f-text002">Contact</a>
          <a href="#" ><img src="{% static 'museyapp/img/footer-logo.png'%}"></a>
        </div>
      </div>
    </footer> 
{% endblock %}     


museyapp/templates/museyapp/index.html

{% extends "museyapp/base.html" %}
{% load static %}
{% block content %}
    <div id="page">
      <div id="content">
        <section id="top">
          <div class="row-fluid black-box">
            <div class="container">
              <div class="pull-center">
                <a href="/"><img src=" {% static 'museyapp/img/musey-logo.png' %}" ></a>
                <div class="menu-btn">
                <a href="#menu" class="menu-btn"><img src=" {% static 'museyapp/img/menu-btn.png' %}"></a></p>
              </div>
                
              </div>
              
            </div>
          </div>
        </section>
      </div>
      <nav id="menu">
        <ul>
          <li class="Selected"><a href="musey/events"><span class="home-icon"></span>Home</a></li>
          <li><a href="signup/" style="position:relative"><span class="singup-icon"></span>Sign up</a><div style="left: 28%;
    position: absolute;
    top: 11px;"> <span style="float:left">|</span> <a href="login/" style="color:rgba(255, 255, 255, 0.5); margin-left:10px">{{login}}</a></div></li>
          <li><a href="account-setting.html"><span class="accounts-icon"></span>Account settings</a></li>
        </ul>
        <div class="nav-musey-logo"><a href="/"><img src=" {% static 'museyapp/img/nav-musey-logo.png' %}"></a></div>
      </nav>
    </div>  
    <div class="container m-bg">
      <img src=" {% static 'museyapp/img/titled-bg-top.png' %}" class="">
      <div class="tbg-bottom">
          <h2>MUSEY</h2>
          <p>
          disrupts the existing relationship between art & culture and value.
          </p>
      </div>
      <img src=" {% static 'museyapp/img/titled-bg-bottom.png' %}" class="top-bg">
      <a class="gs-btn" href="/musey/events">Get started</a>
    </div>
    
{% endblock %}  
   <!--
    <footer class="container-fluid fotternav">
      <div class="container">
        <div class="f-nav">
          <a href="artist-kingkong3.html" class="f-text002">About us</a>
          <a href="mailto:someone@example.com?Subject=Hello%20again" target="_top" class="f-text002">Contact</a>
          <a href="#" ><img src=" {% static 'img/footer-logo.png"></a>
        </div>
      </div>
    </footer> -->
   


museyapp/templates/museyapp/projects.html
{% extends "museyapp/base.html" %}
{% load static %}
{% block content %}
    <div id="page">
      <div id="content">
        <section id="top">
          <div class="row-fluid black-box">
            <div class="container" style="position:relative">
              <div class="pull-center">
                <a href="../index.html"><img src="{% static 'museyapp/img/musey-logo.png'%}" ></a>
                <div class="menu-btn">
                <a href="event-onafence.html" class="menu-btn m-arrow"><img src="{% static 'museyapp/img/menu-left-arrow.png'%}"></a>
                <!--
                <a href="#menu" class="menu-btn"><img src="../img/menu-btn.png"></a>-->
              </div>
                
              </div>
              
            </div>
          </div>
        </section>
      </div>
      <nav id="menu">
        <ul>
          <li class="Selected"><a href="../index.html"><span class="home-icon"></span>Home</a></li>
          <li><a href="signup.html"><span class="singup-icon"></span>Sign up | Log in</a></li>
          <li><a href="account-setting.html"><span class="accounts-icon"></span>Account settings</a></li>
        </ul>
        <div class="nav-musey-logo"><a href="../index.html"><img src="{% static 'museyapp/img/nav-musey-logo.png'%}"></a></div>
      </nav>
    </div>  
    
    <div class="container home-bottom">
      <img src={{event_img.image.url}}>
      <a href="#" class="share-box">Share this</a>
      <div class="e-detail">
        <div class="event-title">
          <h3 class="subpages_title">{{event.main_title}}</h3>
          <h6>{{event.Subtitle}}</h6>
        </div>
      </div>
      <a class="grey-btn"><img src="{% static 'museyapp/img/g-pin.png'%}" class="gpin">{{event.Location}}</a>
      <a class="grey-btn2">{{event.datefrom}} - {{event.dateto}}</a>
      <a class="grey-btn2">{{event.timefrom}} - {{event.timeto}}</a>
      
      <div class="p-mi">
        <h6>More Info</h6>
        <p>{{event.Description}}
        </p>
        <div class="p-mi-bottom">
          {% for e_artist in event.event_artist_set.all %}
        <div class="links">
        <h2 class="pull-left">{{e_artist.artist.first_name}} {{e_artist.artist.last_name}}</h2>
        <a class="pnext-arrow" href="/musey/artists/{{e_artist.artist.id}}"><img src="{% static 'museyapp/img/small-right-arrow.png'%}" style="max-width: 100%;"></a>
        </div>
        <p>{{e_artist.artist.statement}}</p>
        {% endfor %}
      </div>
        
      </div>
      <a class="gs-btn" href="project-onafence-thankyou.html">Say "Thanks" to {{event.Subtitle}}</a>
     

    </div>
    <footer class="container-fluid fotternav">
      <div class="container">
        <div class="f-nav">
          <a href="about.html" class="f-text002">About us</a>
          <a href="mailto:someone@example.com?Subject=Hello%20again" target="_top" class="f-text002">Contact</a>
          <a href="#" ><img src="{% static 'museyapp/img/footer-logo.png'%}"></a>
        </div>
      </div>
    </footer> 
   
{% endblock %}  

museyapp/templates/museyapp/thankyou.html
{% extends "museyapp/base.html" %}
{% load static %}
{% block content %}
    <div id="page">
      <div id="content">
        <section id="top">
          <div class="row-fluid black-box">
            <div class="container">
              <div class="pull-center">
                <a href="../index.html"><img src="../img/musey-logo.png" ></a>
                <div class="menu-btn">
                <a href="project-onafence.html" class="menu-btn m-arrow"><img src="../img/menu-left-arrow.png"></a>
                <!--
                <a href="#menu" class="menu-btn"><img src="../img/menu-btn.png"></a>-->
              </div>
                
              </div>
              
            </div>
          </div>
        </section>
      </div>
      
    </div>  
    
    <div class="container home-bottom">
      <img src="../img/onafence-event.jpg">
      <a href="#" class="share-box">Share this</a>
      <div class="e-detail">
        <div class="event-title">
          <h3 class="subpages_title">{{event.main_title}}</h3>
          <h6>{{event.Subtitle}}</h6>
          <div class="bottom-divider"></div>
          {% for e_artist in event.event_artist_set.all %}
          <div class="thankyou-text">
            {{e_artist.artist.first_name}} {{e_artist.artist.last_name}}
          </div>
          {% endfor %}
          <div class="thankt-1">
          <h3>THANK YOU,</h3>
          <h3>Wes</h3>
          <p>Hey, do you want to help us make more of these experiences happen for others?</p>
          <div>
          <a class="d-block">$2</a>
          <a class="d-block">$5</a>
          <a class="d-block">$10</a>
          </div>
          <div>
          <a class="d-block">$20</a>
          <a class="d-block">$5</a>
          <a class="d-block">other</a>
          </div>
          </div>
        </div>
      </div>

        
      </div>

    </div>

    <footer class="container-fluid fotternav">
      <div class="container">
        <div class="f-nav">
          <a href="about.html" class="f-text002">About us</a>
          <a href="mailto:someone@example.com?Subject=Hello%20again" target="_top" class="f-text002">Contact</a>
          <a href="event-kingkong.html" ><img src="../img/footer-logo.png"></a>
        </div>
      </div>
    </footer> 
   
{% endblock %} 